# -*- coding: utf-8 -*-
# Variables for the Audacity App Module for NVDA
# Copyright 2017 Robert Hänggi and NVDA Access

canditatesStartTime = [
	'Add Label At Playback Position',
	'Play/Stop And Set Cursor',
	'Selection Start',
	'Selection End',
	'Track Start',
	'Track End',
	'Project Start',
	'Project End',
	'Previous Clip Boundary',
	'Next Clip Boundary',
	'Short Seek Left During Playback',
	'Long Seek Left During Playback',
	'Selection Extend Left',
	'Set (Or Extend) Left Selection',
	'Left At Playback Position', 
	'Selection Contract Left',
	'Cursor Left',
	'Cursor Short Jump Left',
	'Cursor Long Jump Left',
	'Clip Left',
	'Clip Right',
]
canditatesEndTime = [
	'Short Seek Right During Playback',
	'Cursor Right',
	'Selection Extend Right',
	'Set (Or Extend) Right Selection',
	'Right At Playback Position', 
	'Selection Contract Right',
	'Long Seek Right During Playback',
	'Cursor Short Jump Right',
	'Cursor Long Jump Right',
]

canditatesLength = [
	'Selection To Start',
	'Selection To End',
	'Track Start To Cursor',
	'Cursor To Track End',
]

# Don't speak e.g. "Stopped" after a cut preview or similar.
shouldNotReportStatus = [
	'Play Cut Preview', 
	'Play Cut Preview-At-Speed',
	'Play One Second', 
	'Play Before Selection Start', 
	'Play After Selection Start', 
	'Play Before And After Selection Start', 
	'Play Before Selection End', 
	'Play After Selection End', 
	'Play Before And After Selection End', 
	'Play To Selection',
]

shouldNotAutoSpeak = shouldNotReportStatus+[
	'Cursor Left', 
	'Cursor Short Jump Left', 
	'Cursor Long Jump Left', 
	'Set (Or Extend) Left Selection', 
	'Left At Playback Position', 
	'Selection Extend Left', 
	'Selection Contract Left',
	'Short Seek Left During Playback',
	'Long Seek Left During Playback',
	'Cursor Right', 
	'Cursor Short Jump Right', 
	'Cursor Long Jump Right', 
	'Set (Or Extend) Right Selection', 
	'Selection Extend Right', 
	'Selection Contract Right', 
	'Short Seek Right During Playback',
	'Long Seek Right During Playback',
	'Right At Playback Position', 
	'Pause', 
	'Play/Stop', 
	'Loop Play', 
	'Previous Clip Boundary', 
	'Next Clip Boundary', 
	'Cursor To Next Clip Boundary', 
	'Previous Clip Boundary To Cursor', 
	'Previous Clip', 
	'Next Clip', 
	'Move To Previous Label', 
	'Move To Next Label', 
	#'Change Recording Channels', 
	'Move Focus To Previous Track', 
	'Move Focus To Previous And Select', 
	'Move Focus To Next Track', 
	'Move Focus To Next And Select', 
	'Toggle Focused Track', 
	'Mute/Unmute Focused Track', 
	'Solo/Unsolo Focused Track', 
	'Move Forward From Toolbars To Tracks', 
	'Move Backward From Toolbars To Tracks', 
	'Open Menu On Focused Track', 
	'Record', 
	'Append Record', 
	'Report Selection Start', 
	'Report Selection Length', 
	'Report Selection End', 
	'Report Gain', 
	'Report Pitch', 
	'Report True Peak', 
	'Report Peak Level', 
	'Report Tempo', 
	'Report Pan', 
	'Report True Pan...', 
	'Report Rms', 
	'Report True Rms', 
	'Report Stereo Width...', 
	'Report Correlation', 
] 

