# -*- coding: utf-8 -*-
# Variables for the Audacity App Module for NVDA
# Copyright 2017 Robert Hänggi and NVDA Access

canditatesStartTime = [
	'Add Label At Playback Position',
	'Play/Stop and Set Cursor',
	'Selection Start',
	'Selection End',
	'Track Start',
	'Track End',
	'Project Start',
	'Project End',
	'Previous Clip Boundary',
	'Next Clip Boundary',
	'Short seek left during playback',
	'Long seek left during playback',
	'Selection Extend Left',
	'Set (or Extend) Left Selection',
	'Left at Playback Position', 
	'Selection Contract Left',
	'Cursor Left',
	'Cursor Short Jump Left',
	'Cursor Long Jump Left',
	'Clip Left',
	'Clip Right',
]
canditatesEndTime = [
	'Short seek right during playback',
	'Cursor Right',
	'Selection Extend Right',
	'Set (or Extend) Right Selection',
	'Right at Playback Position', 
	'Selection Contract Right',
	'Long Seek right during playback',
	'Cursor Short Jump Right',
	'Cursor Long Jump Right',
]

canditatesLength = [
	'Selection to Start',
	'Selection to End',
	'Track Start to Cursor',
	'Cursor to Track End',
]

# Don't speak e.g. "Stopped" after a cut preview or similar.
shouldNotReportStatus = [
	'Play Cut Preview', 
	'Play Cut Preview-at-Speed',
	'Play One Second', 
	'Play Before Selection Start', 
	'Play After Selection Start', 
	'Play Before and After Selection Start', 
	'Play Before Selection End', 
	'Play After Selection End', 
	'Play Before and After Selection End', 
	'Play To Selection',
]

shouldNotAutoSpeak = shouldNotReportStatus+[
	'Cursor Left', 
	'Cursor Short Jump Left', 
	'Cursor Long Jump Left', 
	'Set (or Extend) Left Selection', 
	'Left at Playback Position', 
	'Selection Extend Left', 
	'Selection Contract Left',
	'Short seek left during playback',
	'Long seek left during playback',
	'Cursor Right', 
	'Cursor Short Jump Right', 
	'Cursor Long Jump Right', 
	'Set (or Extend) Right Selection', 
	'Selection Extend Right', 
	'Selection Contract Right', 
	'Short seek right during playback',
	'Long seek right during playback',
	'Right at Playback Position', 
	'Pause', 
	'Play/Stop', 
	'Loop Play', 
	'Previous Clip Boundary', 
	'Next Clip Boundary', 
	'Cursor to Next Clip Boundary', 
	'Previous Clip Boundary to Cursor', 
	'Previous Clip', 
	'Next Clip', 
	'Move to Previous Label', 
	'Move to Next Label', 
	#'Change recording channels', 
	'Move Focus to Previous Track', 
	'Move Focus to Previous and Select', 
	'Move Focus to Next Track', 
	'Move Focus to Next and Select', 
	'Toggle Focused Track', 
	'Mute/Unmute focused track', 
	'Solo/Unsolo focused track', 
	'Move forward from toolbars to tracks', 
	'Move backward from toolbars to tracks', 
	'Open menu on focused track', 
	'Record', 
	'Append Record', 
	'Report Selection Start', 
	'Report Selection Length', 
	'Report Selection End', 
	'Report Gain', 
	'Report Pitch', 
	'Report True Peak', 
	'Report Peak Level', 
	'Report Tempo', 
	'Report Pan', 
	'Report True Pan...', 
	'Report RMS', 
	'Report True RMS', 
	'Report Stereo Width...', 
	'Report Correlation', 
] 

# all bottom level commands that can have a shortcut assigned to them.
fullMenuSet = [
	'New',
	'Open...',
	'Clear',
	'Close',
	'Save Project',
	'Save Project As...',
	'Export as MP3',
	'Export as WAV',
	'Export as OGG',
	'Export Audio...',
	'Export Selected Audio...',
	'Export Labels...',
	'Export Multiple...',
	'Export MIDI...',
	'Save Compressed Copy of Project...',
	'Audio...',
	'Labels...',
	'MIDI...',
	'Raw Data...',
	'Apply Chain...',
	'Edit Chains...',
	'Page Setup...',
	'Print...',
	'Exit',
	'Undo',
	'Redo',
	'Cut',
	'Delete',
	'Copy',
	'Paste',
	'Duplicate',
	'Split Cut',
	'Split Delete',
	'Silence Audio',
	'Trim Audio',
	'Split',
	'Split New',
	'Join',
	'Detach at Silences',
	'Edit Labels...',
	'Add Label At Selection',
	'Add Label At Playback Position',
	'Paste Text to New Label',
	'Type to Create a Label (on/off)',
	'Cut',
	'Delete',
	'Split Cut',
	'Split Delete',
	'Silence Audio',
	'Copy',
	'Split',
	'Join',
	'Detach at Silences',
	'Metadata...',
	'Preferences...',
	'All',
	'None',
	'In All Tracks',
	'In All Sync-Locked Tracks',
	'Left at Playback Position',
	'Right at Playback Position',
	'Track Start to Cursor',
	'Cursor to Track End',
	'Store Selection',
	'Retrieve Selection',
	'Toggle spectral selection',
	'Next Higher Peak Frequency',
	'Next Lower Peak Frequency',
	'Previous Clip Boundary to Cursor',
	'Cursor to Next Clip Boundary',
	'Previous Clip',
	'Next Clip',
	'Cursor to Stored Cursor Position',
	'Store Cursor Position',
	'At Zero Crossings',
	'Zoom In',
	'Zoom Normal',
	'Zoom Out',
	'Zoom to Selection',
	'Fit to Width',
	'Fit to Height',
	'Collapse All Tracks',
	'Expand Collapsed Tracks',
	'Selection Start',
	'Selection End',
	'History...',
	'Karaoke...',
	'Mixer Board...',
	'Reset Toolb&ars',
	'Transport Toolbar',
	'Tools Toolbar',
	'Recording Meter Toolbar',
	'Playback Meter Toolbar',
	'Mixer Toolbar',
	'Edit Toolbar',
	'Transcription Toolbar',
	'Scrub Toolbar',
	'Device Toolbar',
	'Selection Toolbar',
	'Spectral Selection Toolbar',
	'Extra Menus (on/off)',
	'Show Clipping (on/off)',
	'Play/Stop',
	'Play/Stop and Set Cursor',
	'Loop Play',
	'Pause',
	'Record',
	'Append Record',
	'Timer Record...',
	'Pause',
	'Scrub',
	'Seek',
	'Scrub Ruler',
	'Selection Start',
	'Selection End',
	'Track Start',
	'Track End',
	'Previous Clip Boundary',
	'Next Clip Boundary',
	'Project Start',
	'Project End',
	'Lock',
	'Unlock',
	'Rescan Audio Devices',
	'Sound Activation Level...',
	'Sound Activated Recording (on/off)',
	'Pinned Play/Record Head (on/off)',
	'Overdub (on/off)',
	'Software Playthrough (on/off)',
	'Mono Track',
	'Stereo Track',
	'Label Track',
	'Time Track',
	'Mix Stereo down to Mono',
	'Mix and Render',
	'Mix and Render to New Track',
	'Resample...',
	'Remove Tracks',
	'Mute All Tracks',
	'Unmute All Tracks',
	'Left',
	'Right',
	'Center',
	'Align End to End',
	'Align Together',
	'Start to Zero',
	'Start to Cursor/Selection Start',
	'Start to Selection End',
	'End to Cursor/Selection Start',
	'End to Selection End',
	'Move Selection with Tracks (on/off)',
	'by Start time',
	'by Name',
	'Sync-Lock Tracks (on/off)',
	'Add / Remove Plug-ins...',
	'Add / Remove Plug-ins...',
	'Repeat Last Effect',
	'Add / Remove Plug-ins...',
	'Report Correlation',
	'Report Frequency',
	'Report Gain',
	'Report Pan',
	'Report Peak Level',
	'Report Pitch',
	'Report RMS',
	'Report Selection End',
	'Report Selection Length',
	'Report Selection Start',
	'Report Stereo Width...',
	'Report Tempo',
	'Report True Pan...',
	'Report True Peak',
	'Report True RMS',
	'Quick Help',
	'Manual',
	'Screenshot Tools...',
	'Run Benchmark...',
	'Audio Device Info...',
	'MIDI Device Info...',
	'Show Log...',
	'Generate Support Data...',
	'Check Dependencies...',
	'Check for Updates...',
	'About Audacity...',
	'Play',
	'Stop',
	'Play One Second',
	'Play To Selection',
	'Play Before Selection Start',
	'Play After Selection Start',
	'Play Before Selection End',
	'Play After Selection End',
	'Play Before and After Selection Start',
	'Play Before and After Selection End',
	'Play Cut Preview',
	'Selection Tool',
	'Envelope Tool',
	'Draw Tool',
	'Zoom Tool',
	'Time Shift Tool',
	'Multi Tool',
	'Next Tool',
	'Previous Tool',
	'Adjust playback volume',
	'Increase playback volume',
	'Decrease playback volume',
	'Adjust recording volume',
	'Increase recording volume',
	'Decrease recording volume',
	'DeleteKey',
	'DeleteKey2',
	'Play-at-Speed',
	'Loop Play-at-Speed',
	'Play Cut Preview-at-Speed',
	'Adjust playback speed',
	'Increase playback speed',
	'Decrease playback speed',
	'Move to Next Label',
	'Move to Previous Label',
	'Short seek left during playback',
	'Short seek right during playback',
	'Long seek left during playback',
	'Long Seek right during playback',
	'Change recording device',
	'Change playback device',
	'Change audio host',
	'Change recording channels',
	'Snap To Off',
	'Snap To Nearest',
	'Snap To Prior',
	'Selection to Start',
	'Selection to End',
	'Selection Extend Left',
	'Selection Extend Right',
	'Set (or Extend) Left Selection',
	'Set (or Extend) Right Selection',
	'Selection Contract Left',
	'Selection Contract Right',
	'Move backward from toolbars to tracks',
	'Move forward from toolbars to tracks',
	'Move Focus to Previous Track',
	'Move Focus to Next Track',
	'Move Focus to First Track',
	'Move Focus to Last Track',
	'Move Focus to Previous and Select',
	'Move Focus to Next and Select',
	'Toggle Focused Track',
	'Toggle Focused Track',
	'Cursor Left',
	'Cursor Right',
	'Cursor Short Jump Left',
	'Cursor Short Jump Right',
	'Cursor Long Jump Left',
	'Cursor Long Jump Right',
	'Clip Left',
	'Clip Right',
	'Change pan on focused track',
	'Pan left on focused track',
	'Pan right on focused track',
	'Change gain on focused track',
	'Increase gain on focused track',
	'Decrease gain on focused track',
	'Open menu on focused track',
	'Mute/Unmute focused track',
	'Solo/Unsolo focused track',
	'Close focused track',
	'Move focused track up',
	'Move focused track down',
	'Move focused track to top',
	'Move focused track to bottom',
	'Full screen (on/off)',
]

silentStateChange=[
	'Play Cut Preview', 
	'Play One Second', 
	'Play Before Selection Start', 
	'Play After Selection Start', 
	'Play Before and After Selection Start', 
	'Play Before Selection End', 
	'Play After Selection End', 
	'Play Before and After Selection End', 
	'Play To Selection', 
]